const masterSystem = [
    {name:"UX",src:"images/system/ux.png"},
    {name:"BX",src:"images/system/bx.png"},
    {name:"CX",src:"images/system/cx.png"}
];

const masterChips = [
{src:'images/chips/Emperor.png',name:'Emperor',weight:4.7},
{src:'images/chips/Hells.png',name:'Hells',weight:1.7},
{src:'images/chips/Wolf.png',name:'Wolf',weight:1.7},
{src:'images/chips/Pegasus.png',name:'Pegasus',weight:1.7},
{src:'images/chips/Dran.png',name:'Dran',weight:1.7},
{src:'images/chips/Sol.png',name:'Sol',weight:1.7},
{src:'images/chips/Perseus.png',name:'Perseus',weight:1.7},
{src:'images/chips/Wizard.png',name:'Wizard',weight:1.7},
{src:'images/chips/Cerberus.png',name:'Cerberus',weight:1.7},
{src:'images/chips/Fox.png',name:'Fox',weight:1.7},
{src:'images/chips/Phoenix.png',name:'Phoenix',weight:1.7},
{src:'images/chips/Bahamut.png',name:'Bahamut',weight:1.7},
{src:'images/chips/Knight.png',name:'Knight',weight:1.7}
];

const masterBlades = [
{name:'KnightMail',src:'images/blades/KnightMail.png',displayName:'KnightMail',blade:'Main',weight:36.7,atk:10,def:65,sta:35,core:'Any',astBlade:'No',system:'UX'},
{name:'ScorpioSpear',src:'images/blades/ScorpioSpear.png',displayName:'ScorpioSpear',blade:'Main',weight:39.6,atk:25,def:55,sta:30,core:'Any',astBlade:'No',system:'UX'},
{name:'ImpactDrake',src:'images/blades/ImpactDrake.png',displayName:'ImpactDrake',blade:'Main',weight:39,atk:75,def:25,sta:10,core:'Any',astBlade:'No',system:'UX'},
[{name:'CobaltDragoon',src:'images/blades/CobaltDragoon.png',displayName:'CobaltDragoon',blade:'Main',weight:37.8,atk:60,def:15,sta:25,core:'Any',astBlade:'No',system:'BX'},
{name:'CobaltDragoon01',src:'images/blades/CobaltDragoon01.png',displayName:'CobaltDragoon',blade:'Main',weight:37.8,atk:60,def:15,sta:25,core:'Any',astBlade:'No',system:'BX'}],
{name:'ClockMirage',src:'images/blades/ClockMirage.png',displayName:'ClockMirage',blade:'Main',weight:37.7,atk:10,def:10,sta:80,core:'Round',astBlade:'No',system:'UX'},
{name:'SharkScale',src:'images/blades/SharkScale.png',displayName:'SharkScale',blade:'Main',weight:37.6,atk:70,def:15,sta:15,core:'Any',astBlade:'No',system:'UX'},
{name:'TyrannoBeat',src:'images/blades/TyrannoBeat.png',displayName:'TyrannoBeat',blade:'Main',weight:37,atk:70,def:35,sta:10,core:'Any',astBlade:'No',system:'BX'},
{name:'TriceraPress',src:'images/blades/TriceraPress.png',displayName:'TriceraPress',blade:'Main',weight:36.5,atk:20,def:65,sta:15,core:'Any',astBlade:'No',system:'BX'},
{name:'TyrannoRoar',src:'images/blades/TyrannoRoar.png',displayName:'TyrannoRoar',blade:'Main',weight:36,atk:60,def:28,sta:12,core:'Any',astBlade:'No',system:'BX'},
{name:'SamuraiCalibur',src:'images/blades/SamuraiCalibur.png',displayName:'SamuraiCalibur',blade:'Main',weight:36,atk:40,def:30,sta:30,core:'Any',astBlade:'No',system:'BX'},
{name:'DranDagger',src:'images/blades/DranDagger.png',displayName:'DranDagger',blade:'Main',weight:35.3,atk:50,def:25,sta:25,core:'Any',astBlade:'No',system:'BX'},
{name:'ViperTail',src:'images/blades/ViperTail.png',displayName:'ViperTail',blade:'Main',weight:34.7,atk:30,def:20,sta:50,core:'Any',astBlade:'No',system:'BX'},
{name:'WeissTiger',src:'images/blades/WeissTiger.png',displayName:'WeissTiger',blade:'Main',weight:34.6,atk:45,def:30,sta:25,core:'Any',astBlade:'No',system:'BX'},
{name:'PhoenixRudder',src:'images/blades/PhoenixRudder.png',displayName:'PhoenixRudder',blade:'Main',weight:34.5,atk:15,def:40,sta:60,core:'Any',astBlade:'No',system:'UX'},
{name:'PteraSwing',src:'images/blades/PteraSwing.png',displayName:'PteraSwing',blade:'Main',weight:34.3,atk:27,def:23,sta:50,core:'Any',astBlade:'No',system:'BX'},
[{name:'GolemRock01',src:'images/blades/GolemRock01.png',displayName:'GolemRock',blade:'Main',weight:34,atk:30,def:60,sta:10,core:'Any',astBlade:'No',system:'UX'},
{name:'GolemRock02',src:'images/blades/GolemRock02.png',displayName:'GolemRock',blade:'Main',weight:34,atk:35,def:65,sta:15,core:'Any',astBlade:'No',system:'UX'}],
{name:'Might',src:'images/blades/Might.png',displayName:'Might',blade:'Main',weight:33.1,atk:25,def:25,sta:25,core:'Any',astBlade:'Yes',system:'CX'},
[{name:'HellsHammer01',src:'images/blades/HellsHammer01.png',displayName:'HellsHammer',blade:'Main',weight:33.9,atk:55,def:30,sta:30,core:'Any',astBlade:'No',system:'UX'},
{name:'HellsHammer02',src:'images/blades/HellsHammer02.png',displayName:'HellsHammer',blade:'Main',weight:33,atk:50,def:25,sta:25,core:'Any',astBlade:'No',system:'UX'}],
{name:'MammothTusk',src:'images/blades/MammothTusk.png',displayName:'MammothTusk',blade:'Main',weight:33,atk:38,def:40,sta:37,core:'Any',astBlade:'No',system:'BX'},
{name:'Blast',src:'images/blades/Blast.png',displayName:'Blast',blade:'Main',weight:32.8,atk:50,def:10,sta:15,core:'Any',astBlade:'Yes',system:'CX'},
{name:'SphinxCowl',src:'images/blades/SphinxCowl.png',displayName:'SphinxCowl',blade:'Main',weight:32.7,atk:35,def:55,sta:10,core:'Any',astBlade:'No',system:'BX'},
[{name:'EclipseUpper',src:'images/blades/EclipseUpper.png',displayName:'Eclipse',blade:'Main',weight:32.3,atk:30,def:20,sta:10,core:'Any',astBlade:'Yes',system:'CX'},
{name:'EclipseSmash',src:'images/blades/EclipseSmash.png',displayName:'Eclipse',blade:'Main',weight:32.3,atk:20,def:30,sta:10,core:'Any',astBlade:'Yes',system:'CX'}],
{name:'WyvernGale',src:'images/blades/WyvernGale.png',displayName:'WyvernGale',blade:'Main',weight:31.9,atk:10,def:40,sta:50,core:'Any',astBlade:'No',system:'BX'},
{name:'Hunt',src:'images/blades/Hunt.png',displayName:'Hunt',blade:'Main',weight:31.6,atk:20,def:10,sta:30,core:'Any',astBlade:'Yes',system:'CX'},
{name:'Brave',src:'images/blades/Brave.png',displayName:'Brave',blade:'Main',weight:31.2,atk:40,def:10,sta:10,core:'Any',astBlade:'Yes',system:'CX'},
{name:'Dark',src:'images/blades/Dark.png',displayName:'Dark',blade:'Main',weight:30.3,atk:10,def:40,sta:10,core:'Any',astBlade:'Yes',system:'CX'},
{name:'Brush',src:'images/blades/Brush.png',displayName:'Brush',blade:'Main',weight:30.3,atk:40,def:15,sta:5,core:'Any',astBlade:'Yes',system:'CX'},
{name:'RockLeone',src:'images/blades/RockLeone.png',displayName:'RockLeone',blade:'Main',weight:30.1,atk:30,def:55,sta:15,core:'Any',astBlade:'No',system:'BX'},
{name:'SharkGill',src:'images/blades/SharkGill.png',displayName:'SharkGill',blade:'Main',weight:29.6,atk:20,def:25,sta:55,core:'Any',astBlade:'No',system:'BX'},
{name:'Arc',src:'images/blades/Arc.png',displayName:'Arc',blade:'Main',weight:29.2,atk:10,def:10,sta:40,core:'Any',astBlade:'Yes',system:'CX'},
{name:'Flare',src:'images/blades/Flare.png',displayName:'Flare',blade:'Main',weight:31.1,atk:25,def:40,sta:10,core:'Any',astBlade:'Yes',system:'CX'},
{name:'DranBuster01',src:'images/blades/DranBuster01.png',displayName:'DranBuster',blade:'Main',weight:36.5,atk:70,def:20,sta:10,core:'Any',astBlade:'No',system:'UX'},
[{name:'HellsScythe',src:'images/blades/HellsScythe.png',displayName:'HellsScythe',blade:'Main',weight:33.7,atk:30,def:35,sta:35,core:'Any',astBlade:'No',system:'BX'},
{name:'HellsScythe02',src:'images/blades/HellsScythe02.png',displayName:'HellsScythe',blade:'Main',weight:33.7,atk:30,def:35,sta:35,core:'Any',astBlade:'No',system:'BX'}],
[{name:'KnightShield',src:'images/blades/KnightShield.png',displayName:'KnightShield',blade:'Main',weight:34.8,atk:20,def:55,sta:25,core:'Any',astBlade:'No',system:'BX'},
{name:'KnightShield01',src:'images/blades/KnightShield01.png',displayName:'KnightShield',blade:'Main',weight:34.8,atk:20,def:55,sta:25,core:'Any',astBlade:'No',system:'BX'}],
{name:'WizardArrow',src:'images/blades/WizardArrow.png',displayName:'WizardArrow',blade:'Main',weight:31.8,atk:15,def:30,sta:55,core:'Any',astBlade:'No',system:'BX'},
{name:'SharkEdge',src:'images/blades/SharkEdge.png',displayName:'SharkEdge',blade:'Main',weight:34.5,atk:65,def:30,sta:20,core:'Any',astBlade:'No',system:'BX'},
{name:'WizardRod',src:'images/blades/WizardRod.png',displayName:'WizardRod',blade:'Main',weight:35.3,atk:15,def:25,sta:60,core:'Any',astBlade:'No',system:'UX'},
{name:'PhoenixWing',src:'images/blades/PhoenixWing.png',displayName:'PhoenixWing',blade:'Main',weight:38,atk:65,def:30,sta:20,core:'Any',astBlade:'No',system:'BX'},
{name:'MeteorDragoon',src:'images/blades/MeteorDragoon.png',displayName:'MeteorDragoon',blade:'Main',weight:39,atk:75,def:15,sta:35,core:'Any',astBlade:'No',system:'UX'},
{name:'BlackShell',src:'images/blades/BlackShell.png',displayName:'BlackShell',blade:'Main',weight:32.4,atk:10,def:65,sta:25,core:'Any',astBlade:'No',system:'BX'},
{name:'SamuraiSaber',src:'images/blades/SamuraiSaber.png',displayName:'SamuraiSaber',blade:'Main',weight:36.5,atk:65,def:20,sta:25,core:'Any',astBlade:'No',system:'UX'},
{name:'MummyCurse',src:'images/blades/MummyCurse.png',displayName:'MummyCurse',blade:'Main',weight:37.5,atk:30,def:60,sta:20,core:'Any',astBlade:'No',system:'UX'},
[{name:'ShelterDrake',src:'images/blades/ShelterDrake.png',displayName:'ShelterDrake',blade:'Main',weight:32.6,atk:25,def:40,sta:35,core:'Any',astBlade:'No',system:'BX'},
{name:'ShelterDrake01',src:'images/blades/ShelterDrake01.png',displayName:'ShelterDrake',blade:'Main',weight:32.6,atk:25,def:40,sta:35,core:'Any',astBlade:'No',system:'BX'}],
{name:'WhaleWave',src:'images/blades/WhaleWave.png',displayName:'WhaleWave',blade:'Main',weight:38.2,atk:45,def:35,sta:20,core:'Any',astBlade:'No',system:'BX'},
{name:'Break',src:'images/blades/Break.png',displayName:'Break',blade:'Over',weight:3.8,atk:10,def:5,sta:5,core:'Any',astBlade:'Yes',system:'CX'},
{name:'Guard',src:'images/blades/Guard.png',displayName:'Guard',blade:'Over',weight:3.4,atk:5,def:10,sta:5,core:'Any',astBlade:'Yes',system:'CX'}
];

const masterAssist = [
{displayName:'Assault',src:'images/assist/Assault.png',name:'Assault',weight:5,atk:25,def:10,sta:5},
{displayName:'Bumper',src:'images/assist/Bumper.png',name:'Bumper',weight:5.3,atk:10,def:20,sta:10},
{displayName:'Dual',src:'images/assist/DualUpper.png',name:'DualUpper',weight:5.9,atk:17,def:13,sta:10},
{displayName:'Dual',src:'images/assist/DualSmash.png',name:'DualSmash',weight:5.9,atk:13,def:17,sta:10},
{displayName:'Free',src:'images/assist/Free.png',name:'Free',weight:5.8,atk:5,def:20,sta:25},
{displayName:'Heavy',src:'images/assist/Heavy.png',name:'Heavy',weight:8.1,atk:17,def:17,sta:11},
{displayName:'Jaggy',src:'images/assist/Jaggy.png',name:'Jaggy',weight:4.9,atk:20,def:15,sta:5},
{displayName:'Round',src:'images/assist/Round.png',name:'Round',weight:4.7,atk:10,def:10,sta:20},
{displayName:'Slash',src:'images/assist/Slash.png',name:'Slash',weight:4.7,atk:20,def:10,sta:10},
{displayName:'Wheel',src:'images/assist/Wheel.png',name:'Wheel',weight:7.2,atk:5,def:15,sta:20},
{displayName:'Zillion',src:'images/assist/Zillion.png',name:'Zillion',weight:6.7,atk:22,def:15,sta:3},
{displayName:'Knuckle',src:'images/assist/Knuckle.png',name:'Knuckle',weight:4.9,atk:30,def:5,sta:5},
{displayName:'Vertical',src:'images/assist/Vertical.png',name:'Vertical',weight:5.3,atk:10,def:25,sta:5}
]

const masterMetalBlade = [
{displayName:'Blitz',src:'images/metal/Blitz.png',name:'Blitz',weight:29.6,atk:25,def:10,sta:5},
{displayName:'Fortress',src:'images/metal/Fortress.png',name:'Fortress',weight:27.7,atk:10,def:20,sta:10}
]

const masterRatchets = [
{src:'images/ratchets/0-60.png',name:'0-60',weight:6.8,atk:3,def:14,sta:13,core:'W',bit:'Yes'},
{src:'images/ratchets/0-70.png',name:'0-70',weight:7,atk:3,def:13,sta:14,core:'W',bit:'Yes'},
{src:'images/ratchets/0-80.png',name:'0-80',weight:7.6,atk:3,def:12,sta:15,core:'W',bit:'Yes'},
{src:'images/ratchets/1-60.png',name:'1-60',weight:6,atk:17,def:9,sta:4,core:'W',bit:'Yes'},
{src:'images/ratchets/1-70.png',name:'1-70',weight:6.1,atk:17,def:6,sta:7,core:'W',bit:'Yes'},
{src:'images/ratchets/1-80.png',name:'1-80',weight:6.7,atk:17,def:4,sta:9,core:'W',bit:'Yes'},
{src:'images/ratchets/2-60.png',name:'2-60',weight:6.2,atk:16,def:8,sta:6,core:'W',bit:'Yes'},
{src:'images/ratchets/2-70.png',name:'2-70',weight:6.4,atk:10,def:12,sta:8,core:'W',bit:'Yes'},
{src:'images/ratchets/2-80.png',name:'2-80',weight:6.9,atk:10,def:11,sta:9,core:'W',bit:'Yes'},
{src:'images/ratchets/3-60.png',name:'3-60',weight:6.4,atk:15,def:9,sta:6,core:'W',bit:'Yes'},
{src:'images/ratchets/3-70.png',name:'3-70',weight:6.4,atk:15,def:8,sta:7,core:'W',bit:'Yes'},
{src:'images/ratchets/3-80.png',name:'3-80',weight:7.1,atk:15,def:7,sta:8,core:'W',bit:'Yes'},
{src:'images/ratchets/3-85.png',name:'3-85',weight:4.7,atk:5,def:15,sta:10,core:'R',bit:'Yes'},
{src:'images/ratchets/4-50.png',name:'4-50',weight:5.9,atk:12,def:13,sta:5,core:'W',bit:'Yes'},
{src:'images/ratchets/4-55.png',name:'4-55',weight:4.8,atk:7,def:11,sta:12,core:'R',bit:'Yes'},
{src:'images/ratchets/4-60.png',name:'4-60',weight:6.3,atk:11,def:13,sta:6,core:'W',bit:'Yes'},
{src:'images/ratchets/4-70.png',name:'4-70',weight:6.4,atk:11,def:12,sta:7,core:'W',bit:'Yes'},
{src:'images/ratchets/4-80.png',name:'4-80',weight:7,atk:11,def:11,sta:8,core:'W',bit:'Yes'},
{src:'images/ratchets/5-60.png',name:'5-60',weight:6.6,atk:12,def:9,sta:9,core:'W',bit:'Yes'},
{src:'images/ratchets/5-70.png',name:'5-70',weight:6.7,atk:12,def:8,sta:10,core:'W',bit:'Yes'},
{src:'images/ratchets/5-80.png',name:'5-80',weight:7.3,atk:12,def:8,sta:10,core:'W',bit:'Yes'},
{src:'images/ratchets/6-60.png',name:'6-60',weight:6.1,atk:14,def:8,sta:8,core:'W',bit:'Yes'},
{src:'images/ratchets/6-70.png',name:'6-70',weight:6.3,atk:14,def:7,sta:9,core:'W',bit:'Yes'},
{src:'images/ratchets/6-80.png',name:'6-80',weight:6.9,atk:14,def:6,sta:10,core:'W',bit:'Yes'},
{src:'images/ratchets/7-55.png',name:'7-55',weight:5.9,atk:6,def:14,sta:10,core:'R',bit:'Yes'},
{src:'images/ratchets/7-60.png',name:'7-60',weight:7.1,atk:8,def:14,sta:8,core:'W',bit:'Yes'},
{src:'images/ratchets/7-70.png',name:'7-70',weight:7.3,atk:8,def:12,sta:10,core:'W',bit:'Yes'},
{src:'images/ratchets/9-60.png',name:'9-60',weight:6.2,atk:13,def:10,sta:7,core:'W',bit:'Yes'},
{src:'images/ratchets/9-65.png',name:'9-65',weight:4.4,atk:13,def:10,sta:7,core:'R',bit:'Yes'},
{src:'images/ratchets/9-70.png',name:'9-70',weight:6.3,atk:13,def:10,sta:7,core:'W',bit:'Yes'},
{src:'images/ratchets/9-80.png',name:'9-80',weight:6.9,atk:13,def:10,sta:7,core:'W',bit:'Yes'},
{src:'images/ratchets/M-85.png',name:'M-85',weight:10.6,atk:8,def:19,sta:13,core:'R',bit:'Yes'},
{src:'images/ratchets/1-50.png',name:'1-50',weight:5.7,atk:18,def:9,sta:3,core:'W',bit:'Yes'},
{src:'images/ratchets/8-70.png',name:'8-70',weight:7.9,atk:8,def:10,sta:12,core:'W',bit:'Yes'},
{src:"images/ratchets/Turbo.png",name:"Tr",weight:12.7,atk:30,def:30,sta:60,dash:10,burstR:30,bit:"No",core:"W"},
[{src:"images/ratchets/OperateATK.png",name:"Op(Atk)",weight:14.1,atk:50,def:35,sta:10,dash:35,burstR:30,bit:"No",core:"W"},
{src:"images/ratchets/OperateDEF.png",name:"Op(Def)",weight:14.1,atk:20,def:50,sta:50,dash:10,burstR:30,bit:"No",core:"W"}]
];

const masterBits = [
{src:'images/bits/Ball.png',name:'Ball',abbr:'B',weight:2.1,atk:15,def:25,sta:50,dash:10,burstR:30},
{src:'images/bits/BoundSpike.png',name:'BoundSpike',abbr:'BS',weight:2,atk:5,def:60,sta:30,dash:5,burstR:30},
{src:'images/bits/Cyclone.png',name:'Cyclone',abbr:'C',weight:2.1,atk:40,def:5,sta:10,dash:45,burstR:80},
{src:'images/bits/DiscBall.png',name:'DiscBall',abbr:'DB',weight:3.2,atk:15,def:20,sta:55,dash:10,burstR:30},
{src:'images/bits/Dot.png',name:'Dot',abbr:'D',weight:2,atk:10,def:55,sta:25,dash:10,burstR:30},
{src:'images/bits/Elevate.png',name:'Elevate',abbr:'E',weight:3.2,atk:30,def:15,sta:20,dash:35,burstR:30},
{src:'images/bits/Flat.png',name:'Flat',abbr:'F',weight:2.2,atk:40,def:15,sta:10,dash:35,burstR:80},
{src:'images/bits/FreeBall.png',name:'FreeBall',abbr:'FB',weight:1.9,atk:10,def:25,sta:60,dash:5,burstR:30},
{src:'images/bits/GearFlat.png',name:'GearFlat',abbr:'GF',weight:2.3,atk:50,def:5,sta:5,dash:40,burstR:80},
{src:'images/bits/GearNeedle.png',name:'GearNeedle',abbr:'GN',weight:2,atk:20,def:40,sta:10,dash:30,burstR:30},
{src:'images/bits/Glide.png',name:'Glide',abbr:'G',weight:2.5,atk:20,def:10,sta:55,dash:15,burstR:30},
{src:'images/bits/Hexa.png',name:'Hexa',abbr:'H',weight:2.6,atk:30,def:35,sta:20,dash:15,burstR:80},
{src:'images/bits/HighNeedle.png',name:'HighNeedle',abbr:'HN',weight:2.2,atk:15,def:55,sta:20,dash:10,burstR:30},
{src:'images/bits/Jolt.png',name:'Jolt',abbr:'J',weight:2.6,atk:35,def:10,sta:15,dash:40,burstR:80},
{src:'images/bits/Kick.png',name:'Kick',abbr:'K',weight:2.2,atk:35,def:25,sta:15,dash:25,burstR:80},
{src:'images/bits/Level.png',name:'Level',abbr:'L',weight:2.7,atk:40,def:5,sta:15,dash:40,burstR:80},
{src:'images/bits/LowFlat.png',name:'LowFlat',abbr:'LF',weight:2.1,atk:45,def:5,sta:10,dash:40,burstR:80},
{src:'images/bits/LowOrb.png',name:'LowOrb',abbr:'LO',weight:2.1,atk:5,def:25,sta:55,dash:15,burstR:30},
{src:'images/bits/LowRush.png',name:'LowRush',abbr:'LR',weight:1.9,atk:45,def:5,sta:15,dash:35,burstR:80},
{src:'images/bits/Merge.png',name:'Merge',abbr:'M',weight:3.4,atk:50,def:20,sta:10,dash:20,burstR:80},
{src:'images/bits/MetalNeedle.png',name:'MetalNeedle',abbr:'MN',weight:2.8,atk:8,def:57,sta:30,dash:5,burstR:30},
{src:'images/bits/Needle.png',name:'Needle',abbr:'N',weight:2,atk:10,def:50,sta:30,dash:10,burstR:30},
{src:'images/bits/Orb.png',name:'Orb',abbr:'O',weight:2,atk:10,def:30,sta:50,dash:10,burstR:30},
{src:'images/bits/Point.png',name:'Point',abbr:'P',weight:2.2,atk:25,def:25,sta:25,dash:25,burstR:80},
{src:'images/bits/RubberAccel.png',name:'RubberAccel',abbr:'RA',weight:3.1,atk:60,def:17,sta:3,dash:20,burstR:80},
{src:'images/bits/Rush.png',name:'Rush',abbr:'R',weight:2.1,atk:40,def:10,sta:20,dash:30,burstR:80},
{src:'images/bits/Spike.png',name:'Spike',abbr:'S',weight:2,atk:10,def:45,sta:35,dash:10,burstR:30},
{src:'images/bits/Taper.png',name:'Taper',abbr:'T',weight:2.2,atk:35,def:20,sta:20,dash:25,burstR:80},
{src:'images/bits/TransKick.png',name:'TransKick',abbr:'TK',weight:2.3,atk:35,def:30,sta:20,dash:15,burstR:80},
{src:'images/bits/UnderFlat.png',name:'UnderFlat',abbr:'UF',weight:2,atk:55,def:5,sta:5,dash:35,burstR:80},
{src:'images/bits/UnderNeedle.png',name:'UnderNeedle',abbr:'UN',weight:1.9,atk:10,def:60,sta:20,dash:10,burstR:30},
{src:'images/bits/Vortex.png',name:'Vortex',abbr:'V',weight:2.2,atk:45,def:10,sta:5,dash:40,burstR:80},
{src:'images/bits/Wedge.png',name:'Wedge',abbr:'W',weight:2.1,atk:5,def:55,sta:30,dash:10,burstR:30},
{src:'images/bits/WallWedge.png',name:'WallWedge',abbr:'WW',weight:2.6,atk:5,def:60,sta:25,dash:10,burstR:30},
{src:'images/bits/Zap.png',name:'Zap',abbr:'Z',weight:2.5,atk:30,def:20,sta:15,dash:35,burstR:80},
{src:'images/bits/Ignition.png',name:'Ignition',abbr:'I',weight:2.4,atk:50,def:15,sta:5,dash:30,burstR:80}
];



const participants = [
 {name:"Aiko",src:"avatars/Aiko.png",sound:["selectVoices/Aiko_1.MP3","selectVoices/Aiko_2.MP3"]},
 {name:"Darian",src:"avatars/Darian.png",sound:["selectVoices/Darian_1.MP3","selectVoices/Darian_2.MP3","selectVoices/Darian_3.MP3"]},
 {name:"Darius",src:"avatars/Darius.png",sound:["selectVoices/Darius_1.MP3","selectVoices/Darius_2.MP3"]},
 {name:"Haruka",src:"avatars/Haruka.png",sound:["selectVoices/Haruka_1.MP3","selectVoices/Haruka_2.MP3","selectVoices/Haruka_3.MP3"]},
 {name:"Jaren",src:"avatars/Jaren.png",sound:["selectVoices/Jaren_1.MP3","selectVoices/Jaren_2.MP3","selectVoices/Jaren_3.MP3"]},
 {name:"Kael",src:"avatars/Kael.png",sound:["selectVoices/Kael_1.MP3","selectVoices/Kael_2.MP3","selectVoices/Kael_3.MP3"]},
 {name:"Kaito",src:"avatars/Kaito.png",sound:["selectVoices/Kaito_1.MP3","selectVoices/Kaito_2.MP3","selectVoices/Kaito_3.MP3"]},
 {name:"Lucian",src:"avatars/Lucian.png",sound:["selectVoices/Lucian_1.MP3","selectVoices/Lucian_2.MP3"]},
 {name:"Mei",src:"avatars/Mei.png",sound:["selectVoices/Mei_1.MP3","selectVoices/Mei_2.MP3","selectVoices/Mei_3.MP3"]},
 {name:"Natsumi",src:"avatars/Natsumi.png",sound:["selectVoices/Natsumi_1.MP3","selectVoices/Natsumi_2.MP3"]},
 {name:"Renji",src:"avatars/Renji.png",sound:["selectVoices/Renji_1.MP3","selectVoices/Renji_2.MP3"]},
 {name:"Ronan",src:"avatars/Ronan.png",sound:["selectVoices/Ronan_2.MP3","selectVoices/Ronan_3.MP3"]},
 {name:"Rose",src:"avatars/Rose.png",sound:["selectVoices/Rose_1.MP3","selectVoices/Rose_2.MP3"]},
 {name:"Ruddy",src:"avatars/Ruddy.png",sound:["selectVoices/Ruddy_1.MP3","selectVoices/Ruddy_2.MP3","selectVoices/Ruddy_3.MP3"]},
 {name:"Ryomaru",src:"avatars/Ryomaru.png",sound:["selectVoices/Ryomaru_1.MP3","selectVoices/Ryomaru_2.MP3","selectVoices/Ryomaru_3.MP3","selectVoices/Ryomaru_4.MP3"]},
 {name:"Sasha",src:"avatars/Sasha.png",sound:["selectVoices/Sasha_1.MP3","selectVoices/Sasha_2.MP3","selectVoices/Sasha_3.MP3"]},
 {name:"Stephanie",src:"avatars/Stephanie.png",sound:["selectVoices/Stephanie_1.MP3","selectVoices/Stephanie_2.MP3","selectVoices/Stephanie_3.MP3"]},
 {name:"Victor",src:"avatars/Victor.png",sound:["selectVoices/Victor_1.MP3","selectVoices/Victor_2.MP3","selectVoices/Victor_3.MP3"]},
 {name:"Wolf",src:"avatars/Wolf.png",sound:["selectVoices/Wolf_1.MP3","selectVoices/Wolf_2.MP3"]},
 {name:"Zera",src:"avatars/Zera.png",sound:["selectVoices/Zera_1.MP3","selectVoices/Zera_2.MP3","selectVoices/Zera_3.MP3"]}
];





